PRAGMA foreign_keys=ON;
BEGIN TRANSACTION;
CREATE TABLE profiles(
ID INTEGER PRIMARY KEY AUTOINCREMENT,
NAME TEXT ,
PASSWORD TEXT  NOT NULL,
EMAIL TEXT   NOT NULL,
WEIGHT INT NOT NULL  DEFAULT 0,
HEIGHT INT NOT NULL DEFAULT 0,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE events(
id INTEGER PRIMARY KEY AUTOINCREMENT,
user_id INT NOT NULL,
category TEXT NOT NULL,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES profiles (id)
);
CREATE TABLE nutrition(
ID INTEGER PRIMARY KEY NOT NULL ,
FOOD TEXT NOT NULL DEFAULT 0,
CALORIES INT  NOT NULL DEFAULT 0,
SUGAR  INT NOT NULL DEFAULT 0,
FAT INT NOT NULL DEFAULT 0,
PROTEIN INT NOT NULL DEFAULT 0,
FIBER INT NOT NULL DEFAULT 0,
CALCIUM INT NOT NULL DEFAULT 0,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE meals(
id INTEGER PRIMARY KEY AUTOINCREMENT,
food_id INT,
serving_amount INT,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
event_id INT NOT NULL,
FOREIGN KEY (event_id) REFERENCES events (id)
);
CREATE TABLE periods(
id INTEGER PRIMARY KEY AUTOINCREMENT,
pain INT NOT NULL DEFAULT 1,
flow_amount INT NOT NULL DEFAULT 3,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
event_id INT NOT NULL,
FOREIGN KEY (event_id) REFERENCES events (id)
);
CREATE TABLE sex_activities(
sex_reference INTEGER PRIMARY KEY AUTOINCREMENT,
rating INT NOT NULL DEFAULT 3,
amount INT NOT NULL DEFAULT 1,
Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
event_id INT NOT NULL,
FOREIGN KEY (event_id) REFERENCES events (id)
);
COMMIT;
